#!/usr/bin/env python3
"""
Disco Icons generator.

Draws every icon of the pack from scratch: a flat rounded-square background
with the app's glyph rebuilt as a "discomorphism" mirror-ball mosaic —
a grid of small mirror tiles with random brightness, dark grout between
tiles, star sparkles and a soft drop shadow.

Runs on GitHub Actions before the APK is built:
    python3 tools/generate_icons.py <output-res-dir> <preview.png>

Every image here is original artwork generated by this code.
"""
import colorsys
import math
import os
import random
import sys

from PIL import Image, ImageChops, ImageDraw, ImageFilter

S = 512  # canvas size in pixels

OUT = sys.argv[1] if len(sys.argv) > 1 else "iconpack/src/main/res/drawable-nodpi"
PREVIEW = sys.argv[2] if len(sys.argv) > 2 else "preview.png"

# Palette (all invented colors, tuned for the disco look)
SILVER = (226, 229, 236)
CHROME = (176, 182, 194)
RED = (218, 40, 46)
GREEN = (44, 200, 100)
BLUE = (58, 108, 220)
YELLOW = (248, 190, 30)
ORANGE = (240, 116, 34)
PURPLE = (150, 84, 222)
CYAN = (36, 178, 208)
DARKBG = (32, 33, 38)
GRAYBG = (232, 233, 238)
NIGHT = (18, 18, 22)


def new_mask():
    return Image.new("L", (S, S), 0)


def mosaic(mask, rgb, cell=26, grout=4, seed=1):
    """Fill the white area of `mask` with mirror tiles of color `rgb`."""
    rnd = random.Random(seed)
    tiles = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(tiles)
    h, s, v = colorsys.rgb_to_hsv(*[c / 255 for c in rgb])
    for y in range(0, S, cell):
        for x in range(0, S, cell):
            cx = min(x + cell // 2, S - 1)
            cy = min(y + cell // 2, S - 1)
            if mask.getpixel((cx, cy)) < 100:
                continue
            if rnd.random() < 0.07:  # occasional pure-mirror sparkle tile
                ss, vv = s * 0.10, 1.0
            else:
                vv = max(0.06, min(1.0, v * rnd.uniform(0.50, 1.30)))
                ss = min(1.0, s * rnd.uniform(0.85, 1.12))
            hh = (h + rnd.uniform(-0.012, 0.012)) % 1.0
            r, g, b = [int(255 * c) for c in colorsys.hsv_to_rgb(hh, ss, vv)]
            d.rectangle(
                [x + grout, y + grout, x + cell - 1, y + cell - 1],
                fill=(r, g, b, 255),
            )
    # dark grout base clipped to the glyph silhouette, tiles on top
    out = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    grout_base = Image.new("RGBA", (S, S), (26, 27, 32, 255))
    out.paste(grout_base, (0, 0), mask)
    alpha = ImageChops.multiply(tiles.split()[3], mask)
    tiles.putalpha(alpha)
    out.alpha_composite(tiles)
    return out


def drop_shadow(mask, dy=12, blur=14, alpha=120):
    sh = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    black = Image.new("RGBA", (S, S), (0, 0, 0, alpha))
    sh.paste(black, (0, dy), mask)
    return sh.filter(ImageFilter.GaussianBlur(blur))


def sparkle_stars(mask, n, seed):
    """A few 4-point light stars on top of the mosaic."""
    rnd = random.Random(seed * 7 + 3)
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    pts, tries = [], 0
    while len(pts) < n and tries < 500:
        tries += 1
        x = rnd.randrange(70, S - 70)
        y = rnd.randrange(70, S - 70)
        if mask.getpixel((x, y)) > 100:
            if all((x - px) ** 2 + (y - py) ** 2 > 90 ** 2 for px, py in pts):
                pts.append((x, y))
    for x, y in pts:
        L = rnd.randrange(24, 42)
        d.line([x - L, y, x + L, y], fill=(255, 255, 255, 235), width=7)
        d.line([x, y - L, x, y + L], fill=(255, 255, 255, 235), width=7)
        h = L // 2
        d.line([x - h, y - h, x + h, y + h], fill=(255, 255, 255, 150), width=3)
        d.line([x - h, y + h, x + h, y - h], fill=(255, 255, 255, 150), width=3)
        d.ellipse([x - 9, y - 9, x + 9, y + 9], fill=(255, 255, 255, 255))
    return img.filter(ImageFilter.GaussianBlur(1))


def background(color, radius=112):
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([10, 10, S - 10, S - 10], radius=radius, fill=color + (255,))
    # soft gloss on the upper half
    gloss = new_mask()
    gd = ImageDraw.Draw(gloss)
    gd.rounded_rectangle([10, 10, S - 10, int(S * 0.46)], radius=radius, fill=34)
    white = Image.new("RGBA", (S, S), (255, 255, 255, 255))
    img.paste(white, (0, 0), gloss)
    # bright rim
    d.rounded_rectangle(
        [10, 10, S - 10, S - 10], radius=radius, outline=(255, 255, 255, 80), width=4
    )
    return img


def rot_rect(d, cx, cy, w, l, ang):
    a = math.radians(ang)
    ca, sa = math.cos(a), math.sin(a)
    pts = []
    for dx, dy in [(-w / 2, -l / 2), (w / 2, -l / 2), (w / 2, l / 2), (-w / 2, l / 2)]:
        pts.append((cx + dx * ca - dy * sa, cy + dx * sa + dy * ca))
    d.polygon(pts, fill=255)


# ---------------------------------------------------------------------------
# Glyphs. Each builder returns a list of (mask, color) layers, drawn in order.
# ---------------------------------------------------------------------------

ICONS = {}


def icon(name, bgcol, nstars=3, cell=26):
    def deco(fn):
        ICONS[name] = (bgcol, fn, nstars, cell)
        return fn
    return deco


@icon("youtube", GRAYBG)
def g_youtube():
    body = new_mask()
    ImageDraw.Draw(body).rounded_rectangle([96, 166, 416, 346], radius=70, fill=255)
    tri = new_mask()
    ImageDraw.Draw(tri).polygon([(218, 204), (218, 308), (322, 256)], fill=255)
    return [(body, RED), (tri, SILVER)]


@icon("chrome", GRAYBG)
def g_chrome():
    box = [112, 112, 400, 400]
    inner = [190, 190, 322, 322]
    layers = []
    for col, a0, a1 in [(RED, 190, 350), (GREEN, 70, 190), (YELLOW, 310, 430)]:
        m = new_mask()
        d = ImageDraw.Draw(m)
        d.pieslice(box, a0, a1, fill=255)
        d.ellipse(inner, fill=0)
        layers.append((m, col))
    hub = new_mask()
    ImageDraw.Draw(hub).ellipse([204, 204, 308, 308], fill=255)
    layers.append((hub, BLUE))
    return layers


@icon("gmail", GRAYBG)
def g_gmail():
    m = new_mask()
    d = ImageDraw.Draw(m)
    w = 48
    d.line([(130, 344), (130, 186)], fill=255, width=w)
    d.line([(382, 344), (382, 186)], fill=255, width=w)
    d.line([(130, 186), (256, 300)], fill=255, width=w)
    d.line([(382, 186), (256, 300)], fill=255, width=w)
    d.ellipse([106, 162, 154, 210], fill=255)
    d.ellipse([358, 162, 406, 210], fill=255)
    return [(m, RED)]


@icon("maps", GRAYBG)
def g_maps():
    m = new_mask()
    d = ImageDraw.Draw(m)
    d.ellipse([166, 106, 346, 286], fill=255)
    d.polygon([(178, 244), (334, 244), (256, 428)], fill=255)
    d.ellipse([226, 166, 286, 226], fill=0)
    return [(m, RED)]


@icon("photos", GRAYBG, nstars=2)
def g_photos():
    defs = [
        ([126, 196, 246, 316], RED),
        ([196, 126, 316, 246], YELLOW),
        ([266, 196, 386, 316], GREEN),
        ([196, 266, 316, 386], BLUE),
    ]
    layers = []
    for box, col in defs:
        m = new_mask()
        ImageDraw.Draw(m).ellipse(box, fill=255)
        layers.append((m, col))
    return layers


@icon("playstore", GRAYBG)
def g_playstore():
    top = new_mask()
    ImageDraw.Draw(top).polygon([(156, 122), (156, 256), (398, 256)], fill=255)
    bot = new_mask()
    ImageDraw.Draw(bot).polygon([(156, 256), (156, 390), (398, 256)], fill=255)
    return [(top, CYAN), (bot, RED)]


@icon("phone", GRAYBG)
def g_phone():
    m = new_mask()
    d = ImageDraw.Draw(m)
    d.arc([130, 200, 382, 460], 20, 160, fill=255, width=74)
    d.ellipse([100, 336, 180, 416], fill=255)
    d.ellipse([332, 336, 412, 416], fill=255)
    m = m.rotate(-42, center=(256, 320))
    return [(m, GREEN)]


@icon("messages", GRAYBG)
def g_messages():
    m = new_mask()
    d = ImageDraw.Draw(m)
    d.rounded_rectangle([106, 136, 406, 340], radius=72, fill=255)
    d.polygon([(160, 320), (250, 320), (140, 408)], fill=255)
    for i in range(3):
        x = 176 + i * 68
        d.ellipse([x, 216, x + 44, 260], fill=0)
    return [(m, BLUE)]


@icon("settings", DARKBG)
def g_settings():
    m = new_mask()
    d = ImageDraw.Draw(m)
    d.ellipse([156, 156, 356, 356], fill=255)
    for ang in (0, 45, 90, 135):
        rot_rect(d, 256, 256, 62, 310, ang)
    d.ellipse([216, 216, 296, 296], fill=0)
    return [(m, SILVER)]


@icon("camera", DARKBG)
def g_camera():
    body = new_mask()
    d = ImageDraw.Draw(body)
    d.rounded_rectangle([106, 176, 406, 386], radius=52, fill=255)
    d.rounded_rectangle([196, 136, 316, 200], radius=26, fill=255)
    d.ellipse([192, 207, 320, 335], fill=0)
    lens = new_mask()
    ImageDraw.Draw(lens).ellipse([204, 219, 308, 323], fill=255)
    flash = new_mask()
    ImageDraw.Draw(flash).ellipse([350, 200, 386, 236], fill=255)
    return [(body, SILVER), (lens, BLUE), (flash, YELLOW)]


@icon("spotify", NIGHT)
def g_spotify():
    m = new_mask()
    d = ImageDraw.Draw(m)
    d.ellipse([116, 116, 396, 396], fill=255)
    d.arc([168, 182, 344, 320], 200, 340, fill=0, width=26)
    d.arc([158, 232, 354, 380], 205, 335, fill=0, width=26)
    d.arc([172, 288, 340, 420], 210, 330, fill=0, width=24)
    return [(m, GREEN)]


@icon("whatsapp", GRAYBG)
def g_whatsapp():
    m = new_mask()
    d = ImageDraw.Draw(m)
    d.ellipse([116, 116, 396, 396], fill=255)
    d.polygon([(150, 330), (196, 396), (128, 400)], fill=255)
    d.ellipse([186, 186, 326, 326], fill=0)
    inner = new_mask()
    di = ImageDraw.Draw(inner)
    di.arc([206, 216, 306, 316], 30, 150, fill=255, width=30)
    di.ellipse([196, 246, 246, 296], fill=255)
    di.ellipse([266, 246, 316, 296], fill=255)
    inner = inner.rotate(-40, center=(256, 266))
    return [(m, GREEN), (inner, SILVER)]


@icon("instagram", (196, 62, 148))
def g_instagram():
    m = new_mask()
    d = ImageDraw.Draw(m)
    d.rounded_rectangle([126, 126, 386, 386], radius=84, fill=255)
    d.rounded_rectangle([168, 168, 344, 344], radius=62, fill=0)
    d.ellipse([200, 200, 312, 312], fill=255)
    d.ellipse([234, 234, 278, 278], fill=0)
    d.ellipse([322, 148, 360, 186], fill=255)
    return [(m, SILVER)]


@icon("x", NIGHT)
def g_x():
    m = new_mask()
    d = ImageDraw.Draw(m)
    d.polygon([(142, 122), (206, 122), (374, 390), (310, 390)], fill=255)
    d.polygon([(310, 122), (374, 122), (206, 390), (142, 390)], fill=255)
    return [(m, SILVER)]


@icon("clock", DARKBG)
def g_clock():
    m = new_mask()
    d = ImageDraw.Draw(m)
    d.ellipse([116, 116, 396, 396], fill=255)
    d.line([(256, 256), (256, 156)], fill=0, width=28)
    d.line([(256, 256), (330, 302)], fill=0, width=28)
    d.ellipse([238, 238, 274, 274], fill=0)
    return [(m, SILVER)]


@icon("calendar", GRAYBG)
def g_calendar():
    body = new_mask()
    d = ImageDraw.Draw(body)
    d.rounded_rectangle([116, 150, 396, 396], radius=44, fill=255)
    for r in range(2):
        for c in range(3):
            x = 172 + c * 76
            y = 240 + r * 72
            d.ellipse([x, y, x + 40, y + 40], fill=0)
    top = new_mask()
    dt = ImageDraw.Draw(top)
    dt.rounded_rectangle([116, 150, 396, 216], radius=30, fill=255)
    pegs = new_mask()
    dp = ImageDraw.Draw(pegs)
    dp.rounded_rectangle([170, 112, 206, 190], radius=16, fill=255)
    dp.rounded_rectangle([306, 112, 342, 190], radius=16, fill=255)
    return [(body, SILVER), (top, RED), (pegs, CHROME)]


@icon("calculator", DARKBG)
def g_calculator():
    body = new_mask()
    d = ImageDraw.Draw(body)
    d.rounded_rectangle([136, 106, 376, 406], radius=44, fill=255)
    for r in range(2):
        for c in range(3):
            x = 172 + c * 62
            y = 250 + r * 62
            d.ellipse([x, y, x + 38, y + 38], fill=0)
    screen = new_mask()
    ImageDraw.Draw(screen).rounded_rectangle([166, 136, 346, 212], radius=18, fill=255)
    return [(body, SILVER), (screen, GREEN)]


@icon("files", GRAYBG)
def g_files():
    back = new_mask()
    d = ImageDraw.Draw(back)
    d.rounded_rectangle([116, 140, 250, 220], radius=24, fill=255)
    d.rounded_rectangle([116, 170, 396, 386], radius=32, fill=255)
    front = new_mask()
    ImageDraw.Draw(front).rounded_rectangle([116, 210, 396, 386], radius=32, fill=255)
    return [(back, BLUE), (front, CYAN)]


@icon("drive", GRAYBG)
def g_drive():
    m = new_mask()
    d = ImageDraw.Draw(m)
    d.polygon([(256, 112), (420, 388), (92, 388)], fill=255)
    d.polygon([(256, 208), (346, 340), (166, 340)], fill=0)
    return [(m, YELLOW)]


@icon("ytmusic", GRAYBG)
def g_ytmusic():
    m = new_mask()
    d = ImageDraw.Draw(m)
    d.ellipse([116, 116, 396, 396], fill=255)
    d.ellipse([172, 172, 340, 340], fill=0)
    tri = new_mask()
    ImageDraw.Draw(tri).polygon([(226, 202), (226, 310), (330, 256)], fill=255)
    return [(m, RED), (tri, SILVER)]


@icon("generic", PURPLE, nstars=2)
def g_generic():
    m = new_mask()
    ImageDraw.Draw(m).polygon(
        [(256, 116), (396, 256), (256, 396), (116, 256)], fill=255
    )
    return [(m, SILVER)]


@icon("appicon", NIGHT, nstars=3, cell=30)
def g_appicon():
    m = new_mask()
    ImageDraw.Draw(m).ellipse([106, 106, 406, 406], fill=255)
    return [(m, SILVER)]


# ---------------------------------------------------------------------------


def make_icon(name, bgcol, layer_fn, nstars, cell, seed):
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    img.alpha_composite(background(bgcol))
    layers = layer_fn()
    union = new_mask()
    for mask, _ in layers:
        union = ImageChops.lighter(union, mask)
    img.alpha_composite(drop_shadow(union))
    for i, (mask, col) in enumerate(layers):
        img.alpha_composite(mosaic(mask, col, cell=cell, seed=seed + i * 13))
    img.alpha_composite(sparkle_stars(union, nstars, seed))
    return img


def main():
    os.makedirs(OUT, exist_ok=True)
    previews = []

    for i, (name, (bgcol, fn, nstars, cell)) in enumerate(ICONS.items()):
        img = make_icon(name, bgcol, fn, nstars, cell, seed=11 + i * 31)
        img.save(os.path.join(OUT, f"{name}.png"))
        previews.append((name, img))
        print("drew", name)

    # iconback: neutral disco tile behind apps without a hand-made icon
    back = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    tile = new_mask()
    ImageDraw.Draw(tile).rounded_rectangle([10, 10, S - 10, S - 10], radius=112, fill=255)
    back.alpha_composite(mosaic(tile, (88, 92, 104), cell=30, seed=99))
    gloss = new_mask()
    ImageDraw.Draw(gloss).rounded_rectangle([10, 10, S - 10, int(S * 0.45)], radius=112, fill=30)
    white = Image.new("RGBA", (S, S), (255, 255, 255, 255))
    back.paste(white, (0, 0), gloss)
    ImageDraw.Draw(back).rounded_rectangle(
        [10, 10, S - 10, S - 10], radius=112, outline=(255, 255, 255, 80), width=4
    )
    back.save(os.path.join(OUT, "iconback.png"))
    previews.append(("iconback", back))

    # iconmask: white = area of the original icon to keep
    maskimg = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    ImageDraw.Draw(maskimg).rounded_rectangle(
        [10, 10, S - 10, S - 10], radius=112, fill=(255, 255, 255, 255)
    )
    maskimg.save(os.path.join(OUT, "iconmask.png"))

    # iconupon: gloss + sparkles laid over every framed icon
    upon = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    gm = new_mask()
    ImageDraw.Draw(gm).rounded_rectangle([10, 10, S - 10, int(S * 0.4)], radius=112, fill=26)
    upon.paste(white, (0, 0), gm)
    full = new_mask()
    ImageDraw.Draw(full).rounded_rectangle([40, 40, S - 40, S - 40], radius=90, fill=255)
    upon.alpha_composite(sparkle_stars(full, 2, seed=5))
    upon.save(os.path.join(OUT, "iconupon.png"))

    print("drew iconback, iconmask, iconupon")

    # contact sheet so humans can eyeball the whole set
    cols, thumb, pad = 6, 200, 16
    names = [n for n, _ in previews]
    rows = (len(previews) + cols - 1) // cols
    sheet = Image.new("RGBA", (cols * (thumb + pad) + pad, rows * (thumb + pad + 26) + pad), (24, 24, 28, 255))
    dd = ImageDraw.Draw(sheet)
    for i, (name, img) in enumerate(previews):
        r, c = divmod(i, cols)
        x = pad + c * (thumb + pad)
        y = pad + r * (thumb + pad + 26)
        sheet.alpha_composite(img.resize((thumb, thumb)), (x, y))
        dd.text((x + 4, y + thumb + 4), name, fill=(220, 220, 225, 255))
    sheet.convert("RGB").save(PREVIEW)
    print("saved preview to", PREVIEW)


if __name__ == "__main__":
    main()
